# Generated by Django 5.0.2 on 2024-06-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_offre_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sous_text_part',
            field=models.CharField(default=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='text_part',
            field=models.CharField(default=False, max_length=200),
            preserve_default=False,
        ),
    ]
