# Generated by Django 5.0.2 on 2024-06-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_service_sous_text_part_service_text_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/outils/')),
            ],
        ),
    ]
