# Generated by Django 5.0.2 on 2024-06-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
