# Generated by Django 5.0.2 on 2024-06-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutilsLangage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/partenaire/')),
            ],
        ),
        migrations.DeleteModel(
            name='Partenaire',
        ),
    ]
