# Generated by Django 5.0.2 on 2024-06-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_outilslangage_delete_partenaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outilslangage',
            name='image',
            field=models.ImageField(upload_to='media/outils/'),
        ),
    ]
